image: "nikolaik/python-nodejs"

before_script:
  - python --version
  - pip install -r requirements_gitlab.txt

stages:
  - Static Analysis
  - Test
  - deploy

mypy:
  stage: Static Analysis
  script:
    - python -m mypy --ignore-missing-imports src/


flake8:
  stage: Static Analysis
  script:
    - flake8 --max-line-length=120 src/

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
    - pylint -d C0301 --errors-only --disable E0401 src/

deploy:
  stage: deploy
  before_script:
    - npm install -g serverless
    - npm install serverless-offline
    - npm install serverless-python-requirements
    - npm install serverless-dynamodb-autoscaling
  script:
    - sls deploy --verbose
