image: docker:19.03.12

stages:
  - Static Analysis
  - Test
  - deploy

mypy:
  stage: Static Analysis
  image: python:3.8
  before_script:
    - pip install -r requirements_gitlab.txt
  script:
    - python -m mypy --ignore-missing-imports src/

flake8:
  stage: Static Analysis
  image: python:3.8
  before_script:
    - pip install -r requirements_gitlab.txt
  script:
    - flake8 --max-line-length=120 src/

pylint:
  stage: Static Analysis
  image: python:3.8
  allow_failure: true
  before_script:
    - pip install -r requirements_gitlab.txt
  script:
    - pylint -d C0301 --errors-only --disable E0401 src/

deploy:
  stage: deploy
  only:
    - master
  services:
    - docker:19.03.12-dind
  variables:
    DOCKER_DRIVER: overlay
  before_script:
    - apk add --no-cache python3 py3-pip
    - apk add --update nodejs nodejs-npm
    - apk update
    - apk upgrade
    - docker info
    - npm install -g serverless
    - npm install serverless-python-requirements
    - npm install serverless-dynamodb-autoscaling
  script:
    - sls deploy --verbose
